# 连接到 GitHub 仓库
backend:
  name: github
  repo: wangxin-oss/rizhi  # 例如：octocat/my-blog
  branch: main  # 你的网站部署分支（通常是 main 或 master）

# 媒体文件存储位置（可选，用于上传图片等）
media_folder: "images/uploads"  # 仓库中存储上传文件的路径
public_folder: "/images/uploads"  # 网页中访问这些文件的路径

# 定义内容类型（以日志为例）
collections:
  - name: "posts"  # 内容类型标识（英文）
    label: "日志"  # 管理界面中显示的名称
    folder: "_posts"  # 日志文件存储的文件夹（需在仓库中创建）
    create: true  # 允许创建新内容
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # 日志文件命名规则（例如：2023-10-01-my-post.md）
    fields:  # 日志的字段（类似表单）
      - {label: "标题", name: "title", widget: "string"}  # 标题字段
      - {label: "发布日期", name: "date", widget: "datetime"}  # 日期字段
      - {label: "日志内容", name: "body", widget: "markdown"}  # 内容字段（支持 Markdown）
